/**
 * This file contains a list of SEMP Attributes to monitor
 */
export const VPN_MONITOR_ATTRIBUTES = 
    [
    /* Connection counts aren't part of the public monitor spec as of yet :( */
    // {id:'msgVpnConnections',text:'Connection Counts'},
    // {id:'msgVpnConnectionsServiceSmf',text:'Connection Count SMF'},
    // {id:'msgVpnConnectionsServiceWeb',text:'Connection Count Web'},
    // {id:'msgVpnConnectionsServiceMqtt',text:'Connection Count MQTT'},
    // {id:'msgVpnConnectionsServiceRestIncoming',text:'Connection Count REST Incoming'},
    // {id:'msgVpnConnectionsServiceRestOutgoing',text:'Connection Count REST Outgoing'},
    // {id:'connectionsServiceAmqp',text:'Connection Count AMQP'},
    {id:'rxMsgRate',text:'Ingress Rate (msgs/second)'},
    {id:'averageRxMsgRate',text:'Avg Ingress Rate (msgs/second)'},
    {id:'rxByteRate',text:'Ingress Rate (bytes/second)'},
    {id:'averageRxByteRate',text:'Avg Ingress Rate (bytes/second)'},
    {id:'txMsgRate',text:'Egress Rate (msgs/second)'},
    {id:'averageTxMsgRate',text:'Avg Egress Rate (msgs/second)'},
    {id:'txByteRate',text:'Egress Rate (bytes/second)'},
    {id:'averageTxByteRate',text:'Avg Egress Rate (bytes/second)'},
    { id: 'discardedRxMsgCount', text: 'Ingress Discards' },
    {id:'discardedTxMsgCount',text:'Egress Discards'},
    {id:'tlsRxByteCount',text:'TLS messages received'},
    {id:'tlsTxByteCount',text:'TLS messages sent'},
    {id:'tlsRxByteRate',text:'TLS ingress rate (bytes/second)'},
    {id:'tlsTxByteRate',text:'TLS egress rate (bytes/second)'},
    {id:'tlsAverageRxByteRate',text:'Avg TLS ingress rate (bytes/second)'},
    {id:'tlsAverageTxByteRate',text:'Avg TLS egress rate (bytes/second)'},
    {id:'rxMsgCount',text:'Total Ingress Client Messages'},
    {id:'txMsgCount',text:'Total Egress Client Messages'},
    {id:'dataRxMsgCount',text:'Ingress Client Data Messages'},
    {id:'dataTxMsgCount',text:'Egress Client Data Messages'},
    {id:'controlRxMsgCount',text:'Ingress Client Control Messages'},
    {id:'controlTxMsgCount',text:'Egress Client Control Messages'},
    {id:'loginRxMsgCount',text:'Ingress Login Messages'},
    {id:'loginTxMsgCount',text:'Egress Login Messages'},
    {id:'rxByteCount',text:'Ingress Total Messages (bytes)'},
    {id:'txByteCount',text:'Egress Total Messages (bytes)'},
    {id:'dataRxByteCount',text:'Ingress Total Client Data Messages (bytes)'},
    {id:'dataTxByteCount',text:'Egress Total Client Data Messages (bytes)'},
    {id:'controlRxByteCount',text:'Ingress Total Client Control Messages (bytes)'},
    {id:'controlTxByteCount',text:'Egress Total Client Control Messages (bytes)'},
    {id:'rxCompressedByteCount',text:'Ingress Compressed Messages (bytes)'},
    {id:'txCompressedByteCount',text:'Egress Compressed Messages (bytes)'},
    {id:'rxUncompressedByteCount',text:'Ingress Uncompressed Messages (bytes)'},
    {id:'txUncompressedByteCount',text:'Egress Uncompressed Messages (bytes)'},
    {id:'rxCompressedByteRate',text:'Ingress Compressed Rate (1s)'},
    {id:'txCompressedByteRate',text:'Egress Compressed Rate (1s)'},
    {id:'rxUncompressedByteRate',text:'Ingress Uncompressed Rate (1s)'},
    {id:'txUncompressedByteRate',text:'Egress Uncompressed Rate (1s)'},
    {id:'averageRxCompressedByteRate',text:'Ingress Compressed Rate (60s)'},
    {id:'averageTxCompressedByteRate',text:'Egress Compressed Rate (60s)'},
    {id:'averageRxUncompressedByteRate',text:'Ingress Uncompressed Rate (60s)'},
    {id:'averageTxUncompressedByteRate',text:'Egress Uncompressed Rate (60s)'}];


    export const CLIENT_MONITOR_ATTRIBUTES = 
    [
    /* Connection counts aren't part of the public monitor spec as of yet :( */
    {id:'rxMsgRate',text:'Ingress Rate (msgs/second)'},
    {id:'averageRxMsgRate',text:'Avg Ingress Rate (msgs/second)'},
    {id:'rxByteRate',text:'Ingress Rate (bytes/second)'},
    {id:'averageRxByteRate',text:'Avg Ingress Rate (bytes/second)'},
    {id:'txMsgRate',text:'Egress Rate (msgs/second)'},
    {id:'averageTxMsgRate',text:'Avg Egress Rate (msgs/second)'},
    {id:'txByteRate',text:'Egress Rate (bytes/second)'},
    {id:'averageTxByteRate',text:'Avg Egress Rate (bytes/second)'},
    {id:'rxDiscardedMsgCount', text: 'Ingress Discards' },
    {id:'noSubscriptionMatchRxDiscardedMsgCount', text: 'Ingress No Subscription Match Discards' },
    {id:'topicParseErrorRxDiscardedMsgCount', text: 'Topic Parse Error Discards' },
    {id:'webParseErrorRxDiscardedMsgCount', text: 'Web Parse Error Discards' },
    {id:'publishTopicAclRxDiscardedMsgCount', text: 'Denied Publish Topic ACL Discards' },
    {id:'msgSpoolCongestionRxDiscardedMsgCount', text: 'Message Spool Congestion Discards' },
    {id:'msgSpoolRxDiscardedMsgCount', text: 'Message Spool Discards' },
    {id:'txDiscardedMsgCount',text:'Egress Discards'},
    {id:'rxMsgCount',text:'Total Ingress Client Messages'},
    {id:'txMsgCount',text:'Total Egress Client Messages'},
    {id:'dataRxMsgCount',text:'Ingress Client Data Messages'},
    {id:'dataTxMsgCount',text:'Egress Client Data Messages'},
    {id:'controlRxMsgCount',text:'Ingress Client Control Messages'},
    {id:'controlTxMsgCount',text:'Egress Client Control Messages'},
    {id:'loginRxMsgCount',text:'Ingress Login Messages'},
    {id:'loginTxMsgCount',text:'Egress Login Messages'},
    {id:'rxByteCount',text:'Ingress Total Messages (bytes)'},
    {id:'txByteCount',text:'Egress Total Messages (bytes)'},
    {id:'dataRxByteCount',text:'Ingress Total Client Data Messages (bytes)'},
    {id:'dataTxByteCount',text:'Egress Total Client Data Messages (bytes)'},
    {id:'controlRxByteCount',text:'Ingress Total Client Control Messages (bytes)'},
    {id:'controlTxByteCount',text:'Egress Total Client Control Messages (bytes)'},
  ];

