/**
 * This file contains a list of SEMP Attributes to monitor
 */
export const VPN_MONITOR_ATTRIBUTES = 
    [
    /* Connection counts aren't part of the public monitor spec as of yet :( */
    // {id:'msgVpnConnections',text:'Connection Counts'},
    // {id:'msgVpnConnectionsServiceSmf',text:'Connection Count SMF'},
    // {id:'msgVpnConnectionsServiceWeb',text:'Connection Count Web'},
    // {id:'msgVpnConnectionsServiceMqtt',text:'Connection Count MQTT'},
    // {id:'msgVpnConnectionsServiceRestIncoming',text:'Connection Count REST Incoming'},
    // {id:'msgVpnConnectionsServiceRestOutgoing',text:'Connection Count REST Outgoing'},
    // {id:'connectionsServiceAmqp',text:'Connection Count AMQP'},
    {id:'rate.rxMsgRate',text:'Ingress Rate (msgs/second)'},
    {id:'rate.averageRxMsgRate',text:'Avg Ingress Rate (msgs/second)'},
    {id:'rate.rxByteRate',text:'Ingress Rate (bytes/second)'},
    {id:'rate.averageRxByteRate',text:'Avg Ingress Rate (bytes/second)'},
    {id:'rate.txMsgRate',text:'Egress Rate (msgs/second)'},
    {id:'rate.averageTxMsgRate',text:'Avg Egress Rate (msgs/second)'},
    {id:'rate.txByteRate',text:'Egress Rate (bytes/second)'},
    {id:'rate.averageTxByteRate',text:'Avg Egress Rate (bytes/second)'},
    {id:'counter.discardedRxMsgCount', text: 'Ingress Discards' },
    {id:'counter.discardedTxMsgCount',text:'Egress Discards'},
    {id:'counter.tlsRxByteCount',text:'TLS messages received'},
    {id:'counter.tlsTxByteCount',text:'TLS messages sent'},
    {id:'rate.tlsRxByteRate',text:'TLS ingress rate (bytes/second)'},
    {id:'rate.tlsTxByteRate',text:'TLS egress rate (bytes/second)'},
    {id:'rate.tlsAverageRxByteRate',text:'Avg TLS ingress rate (bytes/second)'},
    {id:'rate.tlsAverageTxByteRate',text:'Avg TLS egress rate (bytes/second)'},
    {id:'counter.rxMsgCount',text:'Total Ingress Client Messages'},
    {id:'counter.txMsgCount',text:'Total Egress Client Messages'},
    {id:'counter.dataRxMsgCount',text:'Ingress Client Data Messages'},
    {id:'counter.dataTxMsgCount',text:'Egress Client Data Messages'},
    {id:'counter.controlRxMsgCount',text:'Ingress Client Control Messages'},
    {id:'counter.controlTxMsgCount',text:'Egress Client Control Messages'},
    {id:'counter.loginRxMsgCount',text:'Ingress Login Messages'},
    {id:'counter.loginTxMsgCount',text:'Egress Login Messages'},
    {id:'counter.rxByteCount',text:'Ingress Total Messages (bytes)'},
    {id:'counter.txByteCount',text:'Egress Total Messages (bytes)'},
    {id:'counter.dataRxByteCount',text:'Ingress Total Client Data Messages (bytes)'},
    {id:'counter.dataTxByteCount',text:'Egress Total Client Data Messages (bytes)'},
    {id:'counter.controlRxByteCount',text:'Ingress Total Client Control Messages (bytes)'},
    {id:'counter.controlTxByteCount',text:'Egress Total Client Control Messages (bytes)'},
    {id:'counter.rxCompressedByteCount',text:'Ingress Compressed Messages (bytes)'},
    {id:'counter.txCompressedByteCount',text:'Egress Compressed Messages (bytes)'},
    {id:'counter.rxUncompressedByteCount',text:'Ingress Uncompressed Messages (bytes)'},
    {id:'counter.txUncompressedByteCount',text:'Egress Uncompressed Messages (bytes)'},
    {id:'rate.rxCompressedByteRate',text:'Ingress Compressed Rate (1s)'},
    {id:'rate.txCompressedByteRate',text:'Egress Compressed Rate (1s)'},
    {id:'rate.rxUncompressedByteRate',text:'Ingress Uncompressed Rate (1s)'},
    {id:'rate.txUncompressedByteRate',text:'Egress Uncompressed Rate (1s)'},
    {id:'rate.averageRxCompressedByteRate',text:'Ingress Compressed Rate (60s)'},
    {id:'rate.averageTxCompressedByteRate',text:'Egress Compressed Rate (60s)'},
    {id:'rate.averageRxUncompressedByteRate',text:'Ingress Uncompressed Rate (60s)'},
    {id:'rate.averageTxUncompressedByteRate',text:'Egress Uncompressed Rate (60s)'}];


    export const CLIENT_MONITOR_ATTRIBUTES = 
    [
    /* Connection counts aren't part of the public monitor spec as of yet :( */
    {id:'rate.rxMsgRate',text:'Ingress Rate (msgs/second)'},
    {id:'rate.averageRxMsgRate',text:'Avg Ingress Rate (msgs/second)'},
    {id:'rate.rxByteRate',text:'Ingress Rate (bytes/second)'},
    {id:'rate.averageRxByteRate',text:'Avg Ingress Rate (bytes/second)'},
    {id:'rate.txMsgRate',text:'Egress Rate (msgs/second)'},
    {id:'rate.averageTxMsgRate',text:'Avg Egress Rate (msgs/second)'},
    {id:'rate.txByteRate',text:'Egress Rate (bytes/second)'},
    {id:'rate.averageTxByteRate',text:'Avg Egress Rate (bytes/second)'},
    {id:'counter.rxDiscardedMsgCount', text: 'Ingress Discards' },
    {id:'counter.noSubscriptionMatchRxDiscardedMsgCount', text: 'Ingress No Subscription Match Discards' },
    {id:'counter.topicParseErrorRxDiscardedMsgCount', text: 'Topic Parse Error Discards' },
    {id:'counter.webParseErrorRxDiscardedMsgCount', text: 'Web Parse Error Discards' },
    {id:'counter.publishTopicAclRxDiscardedMsgCount', text: 'Denied Publish Topic ACL Discards' },
    {id:'counter.msgSpoolCongestionRxDiscardedMsgCount', text: 'Message Spool Congestion Discards' },
    {id:'counter.msgSpoolRxDiscardedMsgCount', text: 'Message Spool Discards' },
    {id:'counter.txDiscardedMsgCount',text:'Egress Discards'},
    {id:'counter.rxMsgCount',text:'Total Ingress Client Messages'},
    {id:'counter.txMsgCount',text:'Total Egress Client Messages'},
    {id:'counter.dataRxMsgCount',text:'Ingress Client Data Messages'},
    {id:'counter.dataTxMsgCount',text:'Egress Client Data Messages'},
    {id:'counter.controlRxMsgCount',text:'Ingress Client Control Messages'},
    {id:'counter.controlTxMsgCount',text:'Egress Client Control Messages'},
    {id:'counter.loginRxMsgCount',text:'Ingress Login Messages'},
    {id:'counter.loginTxMsgCount',text:'Egress Login Messages'},
    {id:'counter.rxByteCount',text:'Ingress Total Messages (bytes)'},
    {id:'counter.txByteCount',text:'Egress Total Messages (bytes)'},
    {id:'counter.dataRxByteCount',text:'Ingress Total Client Data Messages (bytes)'},
    {id:'counter.dataTxByteCount',text:'Egress Total Client Data Messages (bytes)'},
    {id:'counter.controlRxByteCount',text:'Ingress Total Client Control Messages (bytes)'},
    {id:'counter.controlTxByteCount',text:'Egress Total Client Control Messages (bytes)'},
  ];

